rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - 1.1.x
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python-software-properties
  - sudo apt-get update -y
  - sudo apt-get install -y liblxc0
script:
  - bundle exec rake clean package
